# Generated by Django 6.1.1 on 2026-10-02 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=32)),
                ('fd', models.CharField(max_length=32)),
                ('fp', models.CharField(max_length=32)),
                ('purchase_datetime', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_datetime'],
                'constraints': [models.UniqueConstraint(fields=('fn', 'fd', 'fp'), name='unique_receipt_identifiers')],
            },
        ),
    ]
